CREATE TABLE questions(
    question_id SERIAL PRIMARY KEY,
    question text NOT NULL,
    correct_answer text NOT NULL,
    incorrect_answers json NOT NULL,
    prize INT NOT NULL,
    show_number INT NOT NULL,
    air_date text NOT NULL,
    category text NOT NULL
);

CREATE TABLE pastGames(
    game_id SERIAL PRIMARY KEY,
    questions json NOT NULL,
    date text NOT NULL,
    name text NOT NULL,
    score INT NOT NULL
);

INSERT INTO questions (question_id, question, correct_answer, incorrect_answers, prize, show_number, air_date, category)
VALUES (1, 'The T-bar, the chair & the gondola are 3 types of these devices that transport skiers', 'Lift', '["Conveyors", "Carriers", "Hitches"]', 100, 1739, '03/05/1992', 'Skiing'),
(2, 'Skiers wear these in part to reduce glare & prevent eyestrain', 'Sunglasses', '["Hat", "Headphones", "Contacts"]', 200, 1739, '03/05/1992', 'Skiing'),
(3, '"Cosmetic" name of the light, dry snow that is ideal for skiing', 'Powder', '["Spray", "Mist", "Debris"]', 300, 1739, '03/05/1992', 'Skiing'),
(4, 'In the snowplow method of stopping, a skier brings the tips of their skis together to form this letter', 'V', '["L", "W", "X"]', 400, 1739, '03/05/1992', 'Skiing'),
(5, 'The most basic movement in this type of skiing is the diagonal stride', 'Cross Country Skiing', '["Downhill Skiing", "Alpine Rouring", "Freestyle Skiing"]', 500, 1739, '03/05/1992', 'Skiing'),
(6, 'In 2020 Drake & Lil Durk decided to do this "Now Cry Later', 'Laugh', '["Cry", "Dance", "Sing"]', 100, 8402, '05/18/2021', 'Playing Today''s Hits'),
(7, '"Adore You" was a post-boy band hit for this Brit', 'Harry Styles', '["Niall Horan", "Robbie Williams", "Paul McCartney"]', 200, 8402, '05/18/2021', 'Playing Today''s Hits'),
(8, 'This word preceded "Swings" in a 2020 hit by Pop Smoke; just this word was the title of a No.1 hit by 24Goldn', 'Mood', '["Porch", "Jazz", "Full"]', 300, 8402, '05/18/2021', 'Playing Today''s Hits'),
(9, 'Olivia Rodrigo''s first hit single is this breakup song that debuted at No. 1 in 2021', 'Driver License', '["Good 4 U", "Deja Vu", "Happier"]', 400, 8402, '05/18/2021', 'Playing Today''s Hits'),
(10, 'This country superstar added to his hit parade in 2020 with "Happy Does"', 'Kenny Chesney', '["Chipp Mccapp", "George Strait", "Carrie Underwood"]', 500, 8402, '05/18/2021', 'Playing Today''s Hits'),
(11, 'The title of this 1970s series refers to a wealthy guy on a speakerphone & the 3 women who work as detectives for him', 'Charlie''s Angels', '["Police Woman", "The Rockford Files", "Hawaii Five-O"]', 100, 8405, '05/21/2021', '20th Century TV'),
(12, 'This actor drove the Knight Industries Two Thousand KITT, for short - before heading for the beach in 1989', 'David Hasselhoff', '["Burt Reynolds", "William Shatner", "Brad Pitt"]', 200, 8405, '05/21/2021', '20th Century TV'),
(13, 'Barbara Eden could literally grant Larry Hagman any wish he could think of in this 1960s sitcom... but he wouldn''t let her!', 'I Dream of Jeannie', '["Harper Valley PTA", "Sabrina the Teenage Witch", "Brand New Life"]', 300, 8405, '05/21/2021', '20th Century TV'),
(14, 'In 1980 Tom Hanks came aboard this ABC show as Rick Martin; I hope he tipped Isaac the bartender well', 'The Love Boat', '["Happy Days", "Bosom Buddies", "Cheers"]', 400, 8405, '05/21/2021', '20th Century TV'),
(15, 'Robert Downey Jr. told this lawyer played by Calista Flockhart: "If you need a sympathetic ear, I can fake it"', 'Ally McBeal', '["Dianne Lockhart", "Patty Hewes", "Mia Fey"]', 500, 8405, '05/21/2021', '20th Century TV'),
(16, 'Oregon, Idaho', 'Washington', '["California", "Nevada", "Montana"]', 100, 8215, '05/01/2020', 'States By Borders'),
(17, 'New Hampshire', 'Maine' , '["Rhode Island", "Vermont", "New England"]', 200, 8215, '05/01/2020', 'States By Borders'),
(18, 'Indiana, Ohio, Wisconsin', 'Michigan' , '["Minnesota", "Iowa", "Illinois"]', 300, 8215, '05/01/2020', 'States By Borders'),
(19, 'Connectitcut, Massachusetts', 'Rhode Island' , '["New Hampshire", "New York", "Maine"]', 400, 8215, '05/01/2020', 'States By Borders'),
(20, 'New Mexico, Oklahoma, Arkansas, Lousiana', 'Texas' , '["Utah", "Colorado", "Oregon"]', 500, 8215, '05/01/2020', 'States By Borders'),
(21, 'In fiction, it''s the term for the one who tells the story; first person & third person are 2 types', 'Narrator' , '["Author", "Producer", "Publisher"]', 100, 8206, '04/20/2020', 'Literary Terms'),
(22, 'It''s the practical lesson about right & wrong that results from an instructive story like a fable', 'Moral' , '["Theme", "Lesson", "Parable"]', 200, 8206, '04/20/2020', 'Literary Terms'),
(23, 'From Greek words for "first" & "actor", it''s the main character in a story', 'Protagonist' , '["Thespian", "Truant", "Antagonist"]', 300, 8206, '04/20/2020', 'Literary Terms'),
(24, 'The 6-line "Scottish stanza" is also known by the name of this 18th century poet', 'Burns' , '["Haiku", "Monologue", "Verse"]', 400, 8206, '04/20/2020', 'Literary Terms'),
(25, 'This 5-letter word for a figure of speech is widely used to mean any familiar reference', 'Trope', '["Story", "Irony", "Fable"]', 500, 8206, '04/20/2020', 'Literary Terms');

INSERT INTO questions (question_id, question, correct_answer, incorrect_answers, prize, show_number, air_date, category)
VALUES (26, 'Tomahawk, hatchet', 'Ax', '["Story", "Irony", "Fable"]', 100, 8269, '10/29/2020', 'Weapon Types'),
(27, 'Cutlass, falchion', 'Sword', '["Spear", "Missile", "Flamethrower"]', 200, 8269, '10/29/2020', 'Weapon Types'),
(28, 'Compound, recurve', 'Bow', '["Handgun", "Sniper Rifle", "Torpedo"]', 300, 8269, '10/29/2020', 'Weapon Types'),
(29, 'Bolt action: AR, also called modern sporting', 'Rifle', '["Light Machine Gun", "Bow", "Shotgun"]', 400, 8269, '10/29/2020', 'Weapon Types'),
(30, 'Cudgel, shillelagh', 'Club', '["Rocket", "Grenade", "Sub Machine Gun"]', 500, 8269, '10/29/2020', 'Weapon Types');


INSERT INTO questions (question_id, question, correct_answer, incorrect_answers, prize, show_number, air_date, category)
VALUES (31, 'Generally batting leadoff alphabetically, this "earth pig" has a foot-long tongue', 'Aardvark', '["Tapir", "Anteater", "Mole"]', 100, 8436, '07/05/2021', 'Animals'),
(32, 'Wisconsin''s state mammal, this weasel family member stores up body fat in summer & fall for long winter sleeps', 'Badger', '["Marten", "Otter", "Wolverine"]', 200, 8436, '07/05/2021', 'Animals'),
(33, 'The Indian gray is a type of this mammal that has no problem going after cobras', 'Mongoose', '["Merlin", "Osprey", "Goshawk"]', 300, 8436, '07/05/2021', 'Animals'),
(34, 'Sure, this Aussie mammal lays eggs like a bird, has a bill like a bird & dives under-water for 40 seconds, but flying? Nope!', 'Platypus', '["Echidna", "Hedgehog", "Pangolin"]', 400, 8436, '07/05/2021', 'Animals'),
(35, 'The adorable pygmy monkey lives up to its name; it can be less than a foot long & weight just 10 ounces', 'Marmoset', '["Tamarin", "Lemur", "Tarsier"]', 500, 8436, '07/05/2021', 'Animals'),
(36, '"You''ve Got A Friend In Me" (the original & the sequels)', 'Toy Story', '["The Lion King", "The Little Mermaid", "Aladdin"]', 100, 8436, '07/05/2021', 'Disney Movies By Songs'),
(37, '"Bibbidi Bobbidi Boo"', 'Cinderella', '["Beauty and the Beast", "Fantasia", "Snow White"]', 200, 8436, '07/05/2021', 'Disney Movies By Songs'),
(38, 'It features "You''ll Be In My Heart" by Phil Collins', 'Tarzan', '["Brother Bear", "The Jungle Book 2", "Balto"]', 300, 8436, '07/05/2021', 'Disney Movies By Songs'),
(39, 'Performed by Baloo in the original & in the remake: "The Bare Necessities"', 'The Jungle Book', '["A Goofy Movie", "Lilo & Stitch", "Kronk''s New Groove"]', 400, 8436, '07/05/2021', 'Disney Movies By Songs'),
(40, '"Listen With Your Heart" & "Colors Of The Wind"', 'Pocahontas', '["Atlantis", "Bambi", "The Rescuers"]', 500, 8436, '07/05/2021', 'Disney Movies By Songs'),
(41, 'Don''t place your hot dishes directly on the table; put them on this little stand', 'Trivet', '["Tablet", "Tucket", "Turbit"]', 100, 8436, '07/05/2021', 'Starts & Ends With ''T'''),
(42, 'It means to diagnose a problem you''re having with a computer or an appliance & then solve it', 'Troubleshoot', '["Test", "Target", "Tweet"]', 200, 8436, '07/05/2021', 'Starts & Ends With ''T'''),
(43, 'It''s a small castle tower or something that holds a gun on a military tank', 'Turret', '["Torrent", "Target", "Tippet"]', 300, 8436, '07/05/2021', 'Starts & Ends With ''T'''),
(44, 'Mentioned in "A Wrinkle in Time", it''s a 4-dimensional analogue of a cube, or what Carl Sagan called a hypercube', 'Tesseract', '["Tetravalent", "Transcendent", "Tressiet"]', 400, 8436, '07/05/2021', 'Starts & Ends With ''T'''),
(45, 'From Latin for "to go over", it means temporary or fleeting', 'Transient', '["Turbulent", "Trepidant", "Tremulant"]', 500, 8436, '07/05/2021', 'Starts & Ends With ''T'''),
(46, 'You''ll find this fast food chain''s golden arches at more than 14,000 locations in the U.S. & more than 36,000 worldwide', 'McDonald''s', '["Wendy''s", "Arby''s", "Burger King"]', 100, 8385, '04/23/2021', 'That''s Big Business'),
(47, 'In 2017 this shipping company celebrated the opening of its 5,000th "store"', 'UPS', '["USPS", "Amazon", "Fedex"]', 200, 8385, '04/23/2021', 'That''s Big Business'),
(48, 'In January 2020 this Texas-based convenience store chain announced the opening of its 70,000th location', '7-Eleven', '["Sheetz", "Kum & Go", "Casey''s"]', 300, 8385, '04/23/2021', 'That''s Big Business'),
(49, 'Founded in Virginia in the 1950s, K&K 5&10 experienced some inflation while growing into this nationwide ''Tree''', 'Dollar Tree', '["Euro Tree", "Amero Tree", "Dinero Tree"]', 400, 8385, '04/23/2021', 'That''s Big Business'),
(50, 'In the mid-1800s he joined up with Luigi Rossi, & their spirits business is still going', 'Martini', '["Carpano", "Ransom", "Vermouth"]', 500, 8385, '04/23/2021', 'That''s Big Business'),
(51, 'In "He gave the dog a bone", bone is a direct one of these & dog is an indirect one', 'Object', '["Noun", "Predicate", "Thing"]', 100, 8236, '09/14/2020', 'Sentencing'),
(52, 'In French most adjectives are postpositive, meaning you''ll find them here', 'After the Noun', '["After the Comma", "After the Verb", "After the Preposition"]', 200, 8236, '09/14/2020', 'Sentencing'),
(53, 'Austrian novelist Thomas Bernhard used long sentences; the 2nd sentence of ''Correction'' has 79 of these punctuation marks', 'Commas', '["Semicolons", "Em Dashes", "Hyphens"]', 300, 8236, '09/14/2020', 'Sentencing'),
(54, 'This is the subject at hand; this type of "sentence" tells the main idea of a paragraph', 'Topic', '["Thesis", "Exposition", "Theme"]', 400, 8236, '09/14/2020', 'Sentencing'),
(55, 'The arrangement of words to make a sentence meaningful; in programming, it''s the arrangement of characters so a computer cooperates', 'Syntax', '["Grammar", "Structure", "Pattern"]', 500, 8236, '09/14/2020', 'Sentencing'),
(56, 'NCAA basketball has its Final Four; this sport, its Frozen Four', 'Hockey', '["Lacrosse", "Soccer", "Volleyball"]', 100, 5051, '07/24/2006', 'College Sports'),
(57, 'In 2002 Southern Cal quarterback Carson Palmer won this trophy; Iowa quarterback Brad Banks was second', 'Heisman Trophy', '["Jeweled Shillelagh", "Apple Cup", "The Stanford Axe"]', 200, 5051, '07/24/2006', 'College Sports'),
(58, 'In 1971 UCLA''s Jimmy Connors won the NCAA tennis title; in 1978 John McEnroe won for this Pac-10 ''Cardinal'' school', 'Stanford', '["Notre Dame", "Florida State", "Texas A&M"]', 300, 5051, '07/24/2006', 'College Sports'),
(59, 'The athletic teams from Morehead State & Boston College share this nickname', 'The Eagles', '["The Ravens", "The Trojans", "The Spartans"]', 400, 5051, '07/24/2006', 'College Sports'),
(60, 'This volatile Indiana basketball coach was fired in September 2000; in 2001 he returned to coaching with Texas Tech', 'Bobby Knight', '["Sean Payton", "Billy Martin", "Bill Belichick"]', 500, 5051, '07/24/2006', 'College Sports'),
(61, 'Rock on! All diamonds consist primarily of this element', 'Carbon', '["Silicon", "Oxygen", "Potassium"]', 100, 4838, '09/28/2005', 'Elementary, My Dear'),
(62, 'The U.S. refused to sell this gas to the Zeppelin Aircraft Company, which used the more flammable hydrogen instead', 'Helium', '["Hydrogen", "Carbon", "Nitrogen"]', 200, 4838, '09/28/2005', 'Elementary, My Dear'),
(63, 'It''s the university city in which the element californium was discovered', 'Berkeley', '["M.I.T.", "Harvard", "Stanford"]', 300, 4838, '09/28/2005', 'Elementary, My Dear'),
(64, 'Any old salt could tell you they''re the 2 most abundant elements dissolved in seawater', 'Sodium & Chlorine', '["Hydrogen & Sodium", "Sodium & Oxygen", "Carbon & Sodium"]', 400, 4838, '09/28/2005', 'Elementary, My Dear'),
(65, '1 of the 3 naturally occurring magnetic elements', 'Cobalt', '["Neodymium", "Holmium", "Lead"]', 500, 4838, '09/28/2005', 'Elementary, My Dear');
